using ETLBox;
using ETLBox.DataFlow;
using System.ComponentModel.DataAnnotations.Schema;

namespace MongoToSqlEtl.Models;

public class patientorders : MergeableRow
{
    [Column("_id")]
    [IdColumn]
    [CompareColumn]
    public string id { get; set; }

    [Column("patientorderitems")]
    public string patientorderitems { get; set; }

    [Column("patientdiagnosisuids")]
    public string patientdiagnosisuids { get; set; }

    [Column("ordernumber")]
    public string ordernumber { get; set; }

    [Column("orderdate")]
    public DateTime orderdate { get; set; }

    [Column("orderpriorityuid")]
    public string orderpriorityuid { get; set; }

    [Column("orderpriorityvalue")]
    public string orderpriorityvalue { get; set; }

    [Column("ordertodepartmentuid")]
    public string ordertodepartmentuid { get; set; }

    [Column("patientuid")]
    public string patientuid { get; set; }

    [Column("invstoreuid")]
    public string invstoreuid { get; set; }

    [Column("patientvisituid")]
    public string patientvisituid { get; set; }

    [Column("waitingtime")]
    public DateTime waitingtime { get; set; }

    [Column("orderdepartmentuid")]
    public string orderdepartmentuid { get; set; }

    [Column("overrideorderfromdept")]
    public bool overrideorderfromdept { get; set; }

    [Column("careprovideruid")]
    public string careprovideruid { get; set; }

    [Column("ordermodeuid")]
    public string ordermodeuid { get; set; }

    [Column("ordercattype")]
    public string ordercattype { get; set; }

    [Column("ordertypeuid")]
    public string ordertypeuid { get; set; }

    [Column("ordercommuid")]
    public string ordercommuid { get; set; }

    [Column("userdepartmentuid")]
    public string userdepartmentuid { get; set; }

    [Column("orderinguseruid")]
    public string orderinguseruid { get; set; }

    [Column("isautogenerated")]
    public bool isautogenerated { get; set; }

    [Column("entypeuid")]
    public string entypeuid { get; set; }

    [Column("comments")]
    public string comments { get; set; }

    [Column("printingdiagnosis")]
    public string printingdiagnosis { get; set; }

    [Column("modifiedby")]
    public string modifiedby { get; set; }

    [Column("modifiedat")]
    public DateTime modifiedat { get; set; }

    [Column("createdby")]
    public string createdby { get; set; }

    [Column("createdat")]
    public DateTime createdat { get; set; }

    [Column("statusflag")]
    public string statusflag { get; set; }

    [Column("orguid")]
    public string orguid { get; set; }

    [Column("parentorguid")]
    public string parentorguid { get; set; }

    [Column("prescriptionstatusuid")]
    public string prescriptionstatusuid { get; set; }

    [Column("warduid")]
    public string warduid { get; set; }

    [Column("beduid")]
    public string beduid { get; set; }

    [Column("bedcategoryuid")]
    public string bedcategoryuid { get; set; }

}
