using System;
using System.Collections.Generic;

namespace MongoToSqlEtl.Models;

public partial class StgPatientorder
{
    public string Id { get; set; } = null!;

    public string? Ordernumber { get; set; }

    public DateTime? Orderdate { get; set; }

    public string? Orderpriorityuid { get; set; }

    public string? Orderpriorityvalue { get; set; }

    public string? Ordertodepartmentuid { get; set; }

    public string? Patientuid { get; set; }

    public string? Invstoreuid { get; set; }

    public string? Patientvisituid { get; set; }

    public DateTime? Waitingtime { get; set; }

    public string? Orderdepartmentuid { get; set; }

    public bool? Overrideorderfromdept { get; set; }

    public string? Careprovideruid { get; set; }

    public string? Ordermodeuid { get; set; }

    public string? Ordertypeuid { get; set; }

    public string? Ordercommuid { get; set; }

    public string? Userdepartmentuid { get; set; }

    public string? Orderinguseruid { get; set; }

    public bool? Isautogenerated { get; set; }

    public string? Entypeuid { get; set; }

    public string? Warduid { get; set; }

    public string? Beduid { get; set; }

    public string? Bedcategoryuid { get; set; }

    public string? Comments { get; set; }

    public string? Modifiedby { get; set; }

    public DateTime? Modifiedat { get; set; }

    public string? Createdby { get; set; }

    public DateTime? Createdat { get; set; }

    public string? Statusflag { get; set; }

    public string? Orguid { get; set; }

    public string? Parentorguid { get; set; }

    public string? Prescriptionstatusuid { get; set; }

    public string? Printingdiagnosis { get; set; }
}
